name: Docker Image CI
on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 2 * * *
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ bullseye-slim ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set variables
        id: vars
        working-directory: ${{ matrix.os }}
        run: |
          echo "repository=${GITHUB_ACTOR}/$(basename ${GITHUB_REPOSITORY})" >> $GITHUB_OUTPUT
          echo "version=$(grep ' XXL_VERSION ' Dockerfile | awk -F '[. ]' '{print $3"."$4"."$5}')" >> $GITHUB_OUTPUT
          echo "minor_version=$(grep ' XXL_VERSION ' Dockerfile | awk -F '[. ]' '{print $3"."$4}')" >> $GITHUB_OUTPUT
          echo "major_version=$(grep ' XXL_VERSION ' Dockerfile | awk -F '[. ]' '{print $3}')" >> $GITHUB_OUTPUT
          echo "workdir=${{ matrix.os }}" >> $GITHUB_OUTPUT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ steps.vars.outputs.workdir }}
          pull: true
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ steps.vars.outputs.repository }}:${{ steps.vars.outputs.version }}
            ${{ steps.vars.outputs.repository }}:${{ steps.vars.outputs.minor_version }}
            ${{ steps.vars.outputs.repository }}:${{ steps.vars.outputs.major_version }}
